services:
  # name of service
  backend:
    # build image from current Dockerfile
    build: . 
    # define service port
    ports:
      - "8000:8000"
    # set network
    networks:
      - mynetwork
    # set volume - using host volume
    volumes:
      - ./storage:/var/www/html/storage
      - ./vendor:/var/www/html/vendor
    # set depending service
    depends_on:
      - db
  db:
    # pull image
    image: "mysql:latest"
    # set environment variables
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - mynetwork
    volumes:
      - mysql-data:/var/lib/mysql
  adminer:
    image: "adminer:latest"
    networks:
      - mynetwork
    depends_on:
      - db

networks:
  mynetwork:
    external: true

volumes:
  myvolume:
  mysql-data: