name: Docker Build and Push

on:
  push:
    branches:
      - master
      - 'release/*'  # Trigger on release branches

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Image Tag
        id: set_tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

      - name: Docker build
        run: docker build -t localhost:5000/laravel-product-service:${{ steps.set_tag.outputs.tag }} .
      
      - name: Docker tag
        run: docker tag localhost:5000/laravel-product-service:${{ steps.set_tag.outputs.tag }} localhost:5000/laravel-product-service:latest
        
      - name: Push Docker Image to Local Registry
        run: docker push localhost:5000/laravel-product-service:${{ steps.set_tag.outputs.tag }} && docker push localhost:5000/laravel-product-service:latest

      - name: Deploy to Local Docker Compose
        run: docker-compose -f ${{ secrets.PATH_DOCKER_COMPOSE }}/docker-compose.yml up -d --build
